In [10]:
# numpy examples
import numpy as np

a = [5,8,12,15]

arr1 = np.array(a)

print(type(arr1))
print(arr1)

b = [17,5,21,6]

arr2 = np.array(b)

print(arr2)

c = a+b

arr3 = arr1*arr2

print(c)
print(arr3)

<class 'numpy.ndarray'>
[ 5  8 12 15]
[17  5 21  6]
[5, 8, 12, 15, 17, 5, 21, 6]
[ 85  40 252  90]


In [9]:
# shape

arr1 = np.array([5,8,12,15])

print(arr1.shape)

arr1 = np.array (
    [
        [5,8,12,15],
        [17,5,21,6]
    ]
)

print(arr1)
print(arr1.shape)

arr1 = np.array (
    [
        [
        [5,8,12,15],
        [17,5,21,6]
        ],
        [
        [5,8,12,15],
        [17,5,21,6]
        ],
        [
        [5,8,12,15],
        [17,5,21,6]
        ]
    ]
    
)

print(arr1.shape)

(4,)
[[ 5  8 12 15]
 [17  5 21  6]]
(2, 4)
(3, 2, 4)


In [12]:
#[x1,x2] * [y1,y2]  = (x1*y1+x2*y2)

arr1 = np.array([12,24]).reshape(-1,1)

print(arr1)
print(arr1.shape)

[[12]
 [24]]
(2, 1)


In [14]:
# linspace - generate values between a small range

arr1 = np.linspace(1,10,200)

print(arr1)

[ 1.          1.04522613  1.09045226  1.13567839  1.18090452  1.22613065
  1.27135678  1.31658291  1.36180905  1.40703518  1.45226131  1.49748744
  1.54271357  1.5879397   1.63316583  1.67839196  1.72361809  1.76884422
  1.81407035  1.85929648  1.90452261  1.94974874  1.99497487  2.04020101
  2.08542714  2.13065327  2.1758794   2.22110553  2.26633166  2.31155779
  2.35678392  2.40201005  2.44723618  2.49246231  2.53768844  2.58291457
  2.6281407   2.67336683  2.71859296  2.7638191   2.80904523  2.85427136
  2.89949749  2.94472362  2.98994975  3.03517588  3.08040201  3.12562814
  3.17085427  3.2160804   3.26130653  3.30653266  3.35175879  3.39698492
  3.44221106  3.48743719  3.53266332  3.57788945  3.62311558  3.66834171
  3.71356784  3.75879397  3.8040201   3.84924623  3.89447236  3.93969849
  3.98492462  4.03015075  4.07537688  4.12060302  4.16582915  4.21105528
  4.25628141  4.30150754  4.34673367  4.3919598   4.43718593  4.48241206
  4.52763819  4.57286432  4.61809045  4.66331658  4